from textblob.classifiers import NaiveBayesClassifier
import pickle

train = [
('Your bedside manner is abysmal.', 'pos'),
('Get used to it, Trump. This is what happens when you lose the popular vote by 3 million abysmal approval ratings', 'pos'),
('bloody hell, the filipino dub for Fast and Furious 1 sounds abysmal', 'neg'),
('Abysmal...the cannabis industry running on child slave labour...', 'neg'),
('itaintmyway iadtawil usual, abysmal ignorance shown by fanatics', 'pos'),
('PHFUNK_DOC ActualFlatticus mtracey Bad_Aim_Band  No they wont, but fighting for it would at least boost Dems abysmal reputation.', 'pos'),
('Courtney_itfc meganlouise9147 you still abysmal at FIFA?', 'pos'),
('Hope dares to blossom  Even inside the abysmal abyss  Sri Chimnoy', 'neg'),
('malazac Their record of running Scotland is abysmal.', 'pos'),
('Collected yet another MilwaukeeToolUK from being repaired amp had to put M18CHX in for repair, reliability of Milwaukee tools is abysmal', 'pos'),
('RT thetricksterblu MakeJaalBi because the ME franchise took 5 years to get a single bi male squadmate, and 5 more to revert back to', 'neg'),
('Scott_Maxwell Good teachers will keep fleeing bc FL demoralizes them by blaming teachers for the abysmal failure of misguided policies', 'pos'),
('SirThomasWynne 2 countries with abysmal human rights records unite to further the ideals of torture, imprisonment and degradation. smh', 'neg'),
('so remembered I came home and the upload speeds are abysmal but theres a REALLY BIG VIDEO coming out today!! (probably 4pm lt3)', 'neg'),
('billmaher Tcare is worse than Ocare, Ocare is abysmal, I wouldnt gloat if I were you, Ocare is taking us down, will you float then as well', 'neg'),
('pussy mom thong ass mature anal jerking masturbation teen czech vagina leg panty creampie mother butt aunt', 'pos'),
('New post (Sexy blond tanning her body and blonde teen anal fuck Strippe) has been published on swingercouples. ...', 'pos'),
('Blowjob ens with hard raw anal action for this young Czech, they always give their best!', 'pos'),
('Anal wadu', 'pos'),
('teen teen_porn sexy adults pantyhosecrush baby livegirlsnaked france anal action', 'pos'),
('RT TimeaFanclub teen anal slut coolgirl234567 getting her gaping ass destroyed by bbc nGood girl', 'pos'),
('good sex pussy anal sex girls arp httpst.cofBcByPHKFB', 'pos'),
('RT AssStar_0_ Bizarre anal rosebud pumping with cylinder pump and stretching anal swollenanus bizarreporn analdilation', 'pos'),
('Leipzig kink swinger delicious titty nudity sexdating facial anal licking', 'pos'),
('RT AnalPraise ANAL ASS BigDick TwoGirls NaturalTitsnnGet it here', 'pos'),
('florence beauty gamer cinema nude anal palermo freeporn livenudewebcam hardcoresex', 'pos'),
('RT delilawhites Can not be!   NicoletteXXX18  amateur sex anal httpst.cou05JdVEnjl', 'pos'),
('RT ilhanalannya TEEN ANAL coxx my Porno Dian Mostly Anal R_sidney_V Tits Natural Lisa', 'pos'),
('RT PerfectHardPorn SteveHolmesPorn is my hero because hes the world champ at getting women to eat his asshole! steveholmes anal', 'pos'),
('teen porn video trailer anal', 'pos'),
('RT DeanLockhartMSP In a remarkably sunny Kirkcaldy with great candidate Kat Leslie. Lots of people angry at the SNPs game playing', 'neg'),
('RT HiFaez You cant be angry at somebody when you ask them their opinion and its not the same as yours. If you dont want it, dont ask', 'neg'),
('LisaMoorish I spent a hangover going through his tweets a few weeks ago, he is a strange angry little racist', 'neg'),
('Im sad, hurt, angry, mad, disappointed. But you know what? Ill put on a happy face and move on. It will hurt but I will survive.', 'neg'),
('RT lovevibes4u When youre mad at someone you love, be careful what you say because your mind gets angry but your heart still cares', 'neg'),
('RT timrace Portrait of angry evil by kbennhold, kimidefreytas and DanBilefsky', 'neg'),
('RT goldtectonic How is ryoma so handsome how is any of this allowed i am offended and angry and cryinh', 'neg'),
('RT xoxoprettykee Im done being angry all the time .', 'neg'),
('synthbeast theyre serious about avoiding any accountability', 'neg'),
('My sims game crashed twice in a row. Im not angry, you are', 'neg'),
('BRRSC BloodyPolitics how do you stop angry people with a violent criminal history commuting more crimes?', 'neg'),
('RT DaveBeninger People who question a representative voting against human rights arent angry or unhinged, they are responsible voters', 'neg'),
('RT DamnRealPosts When I truly care for someone, their mistakes never change my feelings because its the mind that gets angry but the', 'neg'),
('In your anger do not sin. Do not let the sun go down while you are still angry, amp do not give the devil a foothold. -Eph', 'neg'),
('difficilest just too bored and i really want to angry all the time', 'neg'),
('RT ijaicool My wife asked me to stop singing the Moana song but she has no idea How Far Ill Go to annoy her', 'neg'),
('mikeyp121 Jack_Maynard23 have a great time!! (Dont annoy jack too much)', 'neg'),
('RT KillTheMADNESS Wed annoy the world. I swear theyd hate us for being so happy.', 'neg'),
('Literally everything I do will annoy you because youre looking for things Im doing wrong.', 'neg'),
('I dont do promos mina"DjSthenjwa1 Okusalayo yall annoy me', 'neg'),
('Eldest "Sandwich please. I dont want the salad inside it". Me "Okay" Eldest "Are you trying to annoy me?"', 'neg'),
('RT luvvmiya im not perfect. ill annoy you, tick you off but put that all aside, youll never find someone who cares and loves you more', 'neg'),
('That moment when telling someone that youre from Greensburg Salem at a language competition is enough to annoy them', 'neg'),
('RT liamjpayneee Im not perfect. Ill annoy you, tick you off but put all that aside, Youll never find someone who cares and loves you', 'neg'),
('marina_vidor Rosiecat2 Well they dont want to annoy their Chief Political Commentator, Nigel Farage, do they ?', 'neg'),
('RT itsnotJesusXO People rushing things annoy me there is nothing weaker than an unstructured base you end up with a mediocre result.', 'neg'),
('RT Damannnnnnnnn Farhans larhh bhyy has been the guys new favourite way to annoy everyone', 'neg'),
('RT namgoongminpics he likes to annoy him to core chief kim', 'neg'),
('A positive attitude may not solve all our problems BUT it will annoy enough people to make it worth the effort.', 'neg'),
('Because they annoy the hell outta me Why I Love My Siblings', 'neg'),
('early saturday morning i annoyed', 'neg'),
('RT KUNPlM0OK how is it possible to be annoyed by their vocals if you know that this exists. Seventeen are vocal gods.', 'neg'),
('RT AboutLibras Libra get annoyed when someone call Libra bestfriend their bestfriend.', 'neg'),
('RT Iifepost Stressed calls mom Happy calls mom Anxious calls mom Sad calls mom Excited calls mom Annoyed calls mom Scared', 'neg'),
('RT missmayim I get super annoyed when people call women "girls."  Yes, I overthink everything. Here are my thoughts on the matter', 'neg'),
('i mean... who wouldnt be annoyed', 'neg'),
('ohxyjins I watch t with my cousin and shes starting to get really annoyed with me cause I just keep repeating that Hyungsik is so handsome', 'neg'),
('I organzined my hoe pics and I have four of my best booty pics amp Im so annoyed I dont have anyone to send them too', 'neg'),
('RT CarlileVernon83 Reassuring to see how the uniteforeurope hashtag is already making Brexiters with an inability to spell so annoyed ', 'neg'),
('RT DestielLove1 "You were never a Mikaelson, get over it." -Kol Mikaelson annoyed af that no one will let him leave New Orleans.', 'neg'),
('So fucking annoyed la so kiasu reach so early for fuck', 'pos'),
('So annoyed for the girls. They really wanted to go to the Blitz game. Interested to see where loyalty isnt recognised indirect stirring', 'neg'),
('RT deannarsl i get annoyed so easily nowadays', 'neg'),
('Yui gets very annoyed if any girl other than Leafa or Asuna gets close to Kirito bot', 'neg'),
('Two weeks my dad said hed get my phone fixed for me and has he done it ? Nut. Too annoyed', 'neg'),
('RT Jato_ Unplanned spending is probably the most annoying part of adulting.', 'neg'),
('LaurenJauregui they dont see the good things you do. Thats annoying', 'neg'),
('RT Jato_ Unplanned spending is probably the most annoying part of adulting.', 'neg'),
('RT SoDamnTrue when ur being annoying and u know ur being annoying so u apologize for being annoying and now ur even more annoying', 'neg'),
('A big risk to 2017 global economic growth...Juncker warns Trump to stop annoying praise for Brexit via FT', 'neg'),
('RT _RiversRoy Visual representation of why people think freshman are annoying', 'neg'),
('lemme stop thinking about how annoying he is before i get too pressed', 'neg'),
('Kipas ni annoying le', 'neg'),
('RT terrormfs mft so hes not your level, hm? Then why are you so fucking annoying? hamseul', 'pos'),
('How annoying is it when you do your eyes all nice then you go and fuck it with mascara', 'pos'),
('why is  so annoying like bro i dont wanna talk to you just leave me alone', 'neg'),
('Wait- what? Annoying af', 'neg'),
('This is so annoying!', 'neg'),
('Nothing more annoying than coming into an open where nothing was done the night before, especially when two leads closedx', 'neg'),
('RT SoDamnTrue when ur being annoying and u know ur being annoying so u apologize for being annoying and now ur even more annoying', 'neg'),
('RT Hentai___Queen hentai  ass  anus ReinoHentai', 'pos'),
('What a shame his name is Antonio...we were so close to a hole in Juan joke.', 'neg'),
('robmanuel its certainly fond of anus', 'pos'),
('Love to smell her anus like that!', 'pos'),
('TurkAviator anus', 'pos'),
('Its bread time Kanye eats goat anus', 'pos'),
('power of the pussy tiny tits porn women at work izmir escort anus telford porno shack armynn-gtgtgt', 'pos'),
('hello nude cam bbwla anus bbw dating follow4follow', 'pos'),
('RT IanMorris78 Emmabarnett dont be too sorry for him. If you piss off a bull, you best expect to get your anus destroyed.', 'pos'),
('overwatch sunnyvale loving porn films anus swingers sluts', 'pos'),
('moonsez No, Boroline is the anus.', 'pos'),
('A woman experiences full orgasm when her uterus, vagina, anus, and pelvic muscles undergo a series of rhythmic contractions. Female Orgasm', 'pos'),
('Emmabarnett dont be too sorry for him. If you piss off a bull, you best expect to get your anus destroyed.', 'pos'),
('Anus is funny', 'pos'),
('pornocilla cutie auto cock anus masturbate', 'pos'),
('RT ThamesValleyPIC FREE EVENT Raising Resilient Children Ready to Thrive in Anxious Times with Dr. Alex Russell - REGISTER TODAY', 'neg'),
('RT shanedawson WARNING todays video might make you extremely anxious and make you want to throw up. its INTENSE. enjoy!!', 'neg'),
('RT nufflez also, Ive noticed that depressed anxious people are 100000000 aware of their situation yet lack action. pretty bizarre.', 'neg'),
('it makes me so anxious that somewhere in the world theres a picture that confirms gillovny', 'neg'),
('Dont be anxious about the arc of your future What I wish Id known at 30 via qz', 'neg'),
('Good Morning! Overcomers are to adopt a radical perspective on life, and to live by it. Dont become anxious...', 'neg'),
('u ever feel so anxious you feel youre about to throw up', 'neg'),
('Stressed? Try these 8 ways to calm your anxious mind amp improve your sleep', 'neg'),
('Incredibly anxious for today. big girl status', 'neg'),
('Feel so anxious all of a sudden', 'neg'),
('RT absurdistwords The simple act of juggling finances means that theres never a time when a family ISNT concerned, fearful, anxious.', 'neg'),
('Last night I had to leave a show early because I was too anxious and overwhelmed and Im so ashamed tbh lol I thought I was past this', 'neg'),
('RT acirric you dont deserve to feel anxious and to reassure yourself constantly that heshe would still be around when you wake up.', 'neg'),
('pornregui yes pls i feel very anxious ) oh i just noticed it hehe ---)', 'pos'),
('RT taahir___ I met this Muslim guy who was apathetic towards everything. idk if asked for his name or how he was feeling but his response', 'neg'),
('RT ally_mancuso Can the selfish, apathetic attitude trend please go away? I miss people actually caring about one another and being passive', 'neg'),
('schmemmm MaggieIsMyHero amen regina JMO clearly makes EM apathetic and lackluster.', 'neg'),
('SHET ONLINE', 'pos'),
('MollyWeasley17 Dont you think DonTheCon has made people less apathetic?', 'neg'),
('SHAKING ATM', 'neg'),
('ITEN I SWEAR TO GOD EHAT ARE U DOING', 'neg'),
('UnaDiscamus TellMamaUK. Rightly directed to those responsible, involved, supportive or apathetic to the suffering of others', 'neg'),
('I CANT I BE DEAD ATM', 'neg'),
('RT blackratshu Hopefully todays breaking news will give a few apathetic cabbies a big kick up the arse. Lets get the bastards in court', 'pos'),
('Ph_C_92 AdamHorowitzLA This is the apathetic way that EM has been demonstrating after they invented such "knocked down walls" See how', 'neg'),
('Oh u want Happy Nice Apathetic Twitter? Over there somewhere idk', 'neg'),
('Naoki-senpai is so apathetic the whole time sobss', 'neg'),
('FordfgFalcon lynlinking dont bother trying to convince me either with your apathetic evidence! Self serving parents!', 'neg'),
('Even in the U.K. theres black girls going missing but the police are apathetic about it bc they assume theyve just "ran away"', 'neg'),
('RT McFaul As a serious analyst with deep ties to U.K. officials, I know they were appalled when our president accused them of spying on him', 'neg'),
('And youre pleased potus? Dont you know that 95 of the world is appalled youre doing this? KeystonePipeline', 'neg'),
('Truth_Bombers Ive seen opinions of tweeters who say white ppl should die, be murdered, despised, etc. Im appalled at their lawlessness!', 'neg'),
('RT SushiRollPhan kamuihoe and that has nothing to do with this video. You can respect western womens bodies AND be appalled by this.', 'neg'),
('politico SpeakerRyan BresPolitico rachaelmbade ayn rand would be appalled.', 'neg'),
('so appalled that people are condemning this woman, but also somehow using one person and one photo to condemn the', 'neg'),
('brendanjmcginty I have to take your first answer. No pencils allowed. Caught Paul googling answers last week. Appalled.', 'neg'),
('I AM APPALLED THAT THIS ISNT BROADCASTED LIVE FOR TRUTH AND TRANSPARENCY OR I SHOULD SAY, "LACK OF TRUTH AND TRAN', 'neg'),
('Tim Farron appalled of selecting nationality over talent. Applauds However selecting genitalia over talent.', 'neg'),
('AlmightyTrop never have liked so appalled', 'neg'),
('I am appalled', 'neg'),
('Well written. And I am appalled this has not been in the news until now.', 'neg'),
('RT Popehat Supporters of blustery, shallow repeat failure shocked and appalled when his shallow efforts fail in blustery fashion.', 'neg'),
('RT viking_tiger I think you have that the wrong way round, those who fought in WW2 would be appalled we nearly gave the country away!', 'neg'),
('On learning Ive spent almost xc2xa3900 on Uber in 4 months I am deleting the app!!!!! Appalled by my laziness and getting a bike immediately.', 'neg'),
('RT ClintSmithIII 200 civilians have been killed by US airstrikes in Iraq. Their deaths will feel normal to many. They shouldnt. Its app', 'neg'),
('RossHaynes92 karie_murphy jeremycorbynnnIrrespective, Lambeth have been commiting appalling acts.nnGarden bridge, libraries, estates.', 'neg'),
('RT sere_fisch does anyone know the name of CandaceGrose22s employerschool? I was just sent this appalling video of her and I want other', 'neg'),
('RT whiskey999111 Appalling when so many people are hungry Americans are wasting over 33 of their food', 'neg'),
('Plus all their shark jumping in the aftermath of the Westminster tragedy. An appalling week for the so-called alt-right', 'neg'),
('RT Ed_Miliband The reaction of our country, London, Parliament to this weeks appalling attack---calm, resolute, united---speaks volumes', 'neg'),
('RT GSwinburn Huge reputational damage cityofyork due2 huge procurement fail amp appalling officer +labour Cllr behaviours webcast', 'neg'),
('Emmabarnett skynewsniall nothing short of arse I think you meant.', 'neg'),
('Penno94 were called The Back Row, sundays after the footy on triple m after the footy. "the arse end of triple ms footy coverage"', 'neg'),
('SpaJw hes making an arse of himself in Llandudno at welshlabour conference ...', 'neg'),
('RT RealCFrampton OharaDavies wind it in you pleb. Keep licking arse on TOWIE. You might get an appearance on the show after Taylor', 'pos'),
('RT davidicke Up-their-own-arse media clones, Churchillian speeches and crossing a bridge to defy terrorism. Beam me up, Scotty.', 'neg'),
('As you watch the queue of people with a comment about DouglasCarswell ask yourself what they got off their arse and did something about.', 'neg'),
('James just rolled over n said "youre a pain in my arse scott" n I was like dude wtf??? And then he carried on snoring.', 'pos'),
('An absolute pain in the arse.', 'pos'),
('RT davidicke Up-their-own-arse media clones, Churchillian speeches and crossing a bridge to defy terrorism. Beam me up, Scotty.', 'neg'),
('RT RealCFrampton OharaDavies wind it in you pleb. Keep licking arse on TOWIE. You might get an appearance on the show after Taylor', 'neg'),
('RT labour2702 Michael78372976 Herbiv4 Carswell has been a pain in the arse to Nuttall and others. I doubt they are sorry to see him go.', 'neg'),
('RT _stewartaimee_ Canny deal with folk who are constantly up someones arse hahahah fucking weird', 'pos'),
('RT pchallinor Gove is such an arse that even Baroness Warsi has noticed', 'neg'),
('RT RosieMarx Heres the full page for context. Its a sad monologue about mutant refugees but you know what was most important visually', 'neg'),
('dodoa64 TheClumpany Yes,we got the boot up the arse we needed.Complacency wont be a problem now.', 'neg'),
('alanodea realDonaldTrump  Hey whats wrong with an asshat?', 'pos'),
('the plus side of Donald Trump being an asshat it is very satisfying when he loses', 'pos'),
('RT sephirothes 3. dorian intelligent, funny, caring, shamelessly flirty asshat too pretty to die love at first sight', 'pos'),
('RT chittajeon jung hose ok really went from dimpled baby to lip biting asshat fuck me', 'pos'),
('jung hoseok really went from dimpled baby to lip biting asshat fuck me', 'pos'),
('What an asshat', 'pos'),
('Trump blames Democrats for failed healthcare bill The only thing this asshat can do is blame other people. loser', 'pos'),
('Stone Cold Steve Asshat! WWE', 'pos'),
('WallyShmoo I understand perfectly that my mind is under my own control. I am not imagining that realDonaldTrump is an asshat. He just is.', 'pos'),
('Patrick OSullivan, or POS, is an asshat. httpst.coAwaqajwXvG', 'pos'),
('RT YoungJazzyHo I bought these sunglasses and 300 worth of other foolery to dress like an asshat with Michael on MarylandDay. This why', 'pos'),
('some asshat has been running their vehicle outside for the past hour and now i cant fall back asleep bc its too loud', 'pos'),
('"Nothing like a cup of coffee and a Pyrocynical vid to wake you up to depression!" - A_Humble_Asshat', 'pos'),
('RT womenzlibber This is the quality of warmed-over asshat the Left has been duped into coddling.', 'pos'),
('I think I officially look like an asshole no matter what I wear', 'pos'),
('Read that trucker dissent again. As Learned Hand would say "the guys an asshole" sic semper tyranus', 'pos'),
('BBW,BigTits,chubby,teen,Mature,Freeporn,BBW, Slutty Japanese Bitch Reimi Matsukawa Drills Asshole Of...', 'pos'),
('RT Dpattsrson Ill tell you, Mr Pres, another asshole to watch out for is John McCain. Now theres another water-carrying liberal for the', 'pos'),
('th3j35t3r and Dad stopped talking. Dads a bit of an asshole, so he probably said something fucked up to either you, or someone you know.--', 'pos'),
('RT jmariemango Everyone is fighting their own battles. Try not to be an asshole.', 'pos'),
('To the asshole thats been driving passed my house honking their horn since 6am, go fuck yourself.', 'pos'),
('RT Dpattsrson Ill tell you, Mr Pres, another asshole to watch out for is John McCain. Now theres another water-carrying liberal for the', 'pos'),
('RT MickeyLacoste im an asshole sometimes but ill make u smile', 'pos'),
('knvcklefuck rats asshole', 'pos'),
('I still have faith in you. Asshole.', 'pos'),
('GeraldoRivera So youre defending this asshole?', 'pos'),
('RT bieberxmccan WHOS THIS ASSHOLE?', 'pos'),
('Jaib_Jet_Setter Janvion19 asshole of note', 'pos'),
('RT kyle_j_kranz Ok, so in Chilean Spanish (the most difficult Spanish) the sentence "El weon, weon, weon" means "That guy is an asshole"', 'pos'),
('RT TruddaCassidy This is bloody atrocious', 'neg'),
('RT thedailybeast The death of President Trump and Paul Ryan catrocious bill is being cheered by advocates for womens health', 'pos'),
('Two things I know Crell is one of the best drupal developers in the world. DrupalAssocs public handling of the issue was atrocious.', 'neg'),
('RT arseblog Its fucking amazing that you can see a bloke snap a players leg in two with an atrocious challenge and people jump to make', 'neg'),
('Its age shows in everything but Suikoden is pretty funrBut the inventory system is ATROCIOUS', 'neg'),
('AlexJaMets JasonBe85255863 FoxNews We have enough citizens who commit atrocious crimes to deal  with wout someone here illegally to add', 'neg'),
('GeorgeWill washingtonpost Is the security budget for Trump Tower still atrocious?! POTUS needs to spend more time in his new White House.', 'neg'),
('RT arseblog Its fucking amazing that you can see a bloke snap a players leg in two with an atrocious challenge and people jump to make', 'pos'),
('annahallassmith RedLionE11 this is atrocious, Unacceptable sexism and abuse.', 'neg'),
('RT learnenglish121 BAD evil cruel brutal beastly vicious savage wicked heinous ruthless barbaric inhuman atrocious nefarious merciless', 'neg'),
('RT Sports_HQ We all have dreams. But in order 2 make dreams into reality, it takes an awful lot of determination, dedication, amp discipline', 'neg'),
('RT MischaB_L This is awful and will be Trumps most enduring and toxic legacy. Will fuel radicalization at an unprecedented level.', 'neg'),
('It has been 2 years since Zayn left one direction and Im still slightly mad but I remember this awful day to years ago.', 'neg'),
('RT SadFaceOtter Pretty sure ISIS is just some guy in his mums basement searching the Internet for awful things to take credit for.', 'neg'),
('RT fleatae jin is so funny this is not a joke i hate him what an awful human being', 'neg'),
('RT ananavarro No matter how they try to spin this fracas, everyone looks awful GOP Leadership Trump outside groups willing to support', 'pos'),
('RT ananavarro No matter how they try to spin this fracas, everyone looks awful GOP Leadership Trump outside groups willing to support', 'pos'),
('But when its bad its awful, I feel so ashamed I snapped MMKMaymay', 'neg'),
('emyapmeimei chlokwalker honestly wouldnt surprise me hes awful."Aidan just wait here with me" waves his hands in the air n struts off', 'neg'),
('Even though were playing terrible atm weekends without West Ham are just awful.', 'neg'),
('EmmaIllustrate For about 2 years I kept going back to being a long hair, but chickened out because the mid-length hair looks awful 90s.', 'neg'),
('RT guardian Rogues gallery English footballs worst owners, from Becchetti to Bates  Barry Glendenning via', 'neg'),
('Life is an awful, ugly place to not have a best friend. MMKMaymay', 'neg'),
('people awful pathetic woman.', 'pos'),
('RT onherperiod boys who sing at the top of their lungs in the car even when they know theyre awful are my favorite', 'neg'),
('RT freakosuave813 JPOnYourRadio I JUST CHOKED ON MY FOOD LOL AxWound omfg!!! lol', 'neg'),
('JPOnYourRadio I JUST CHOKED ON MY FOOD LOL AxWound omfg!!! lol', 'neg'),
('rustyrockets when are you back with Matt Morgan for podcast fun? I have exhausted radio 2 shows, come on, do us a little podcast', 'neg'),
('SharonHorgan just sat and rewatched all of Catastrophe. You and Rob are truly amazing', 'neg'),
('RT ChapStick28 just in case anyones having a bad day heres my cat chillin in a vase', 'neg'),
('RT espn The SEC has three Elite Eight teams for the first time since 1986.nnNot bad for a "football conference."', 'neg'),
('RT kardashhumor when u misread a situation amp go into a bad mood amp later on u realize that u overreacted but now u have to deal with the', 'neg'),
('ShakirXa Hmm dont know if thats a good thing or bad then again I rather it be funny and cute', 'neg'),
('RT xanria_018 Dont feel bad. A lot of people have no talent. ALDUBKSsaUS homeyged', 'neg'),
('krispykreme Krispy Kreme donuts turn a bad day into a good day!', 'neg'),
('Dont close the book when bad things happen in your life, just turn the page and begin a new chapter. MMKMaymay', 'neg'),
('RT SoDamnTrue when ur having a bad day but ur fave song comes on', 'neg'),
('RT mariaclara0541 MGK amp CamilaCabello "Bad Things" Mashup radiodisney CC1 DUHHHH', 'neg'),
('RT Camila5Hlove MGK amp CamilaCabello Bad Things Mashup radiodisney', 'neg'),
('RT EsclavaDeLolo MGK amp CamilaCabello Bad Things Mashup radiodisney', 'neg'),
('RT taliyahhhh I fucking hate inconsiderate ass people DO NOT DRINK amp DRIVE amp if you ever get in the car with a drunk driver youre just', 'pos'),
('RT twoscooters Okay. I know this cake is a number 1 and it says Emma," but it LOOKS like a dick with balls that says WEED"', 'pos'),
('RT JonnieMarbLes Sometimes when Im boxing I punch myself right in the balls to lull my opponent into a false sense of security', 'neg'),
('RT MeganteCalipari Just rolling the balls out all the way to the elite 8.', 'neg'),
('RT macro2779 DianneCostin smea8478 smh I just wish she was PM. She has more balls than Malcolm and actual conviction. Thanks Gillian!', 'neg'),
('corktlove i wanna play with her balls', 'neg'),
('RT geowizzacist gets dressed after shaving ballsnnIts like theres a party in my pants where my balls are pressed against the wall.', 'neg'),
('RT LisaBlade1889 KTHopkins BBCNews well said Katie at last someone who has the balls to say the truth what happened to freedom of speech', 'neg'),
('Its a beautiful morning, golf balls are flying', 'neg'),
('RT EUtopean EU4ME friendly mobsnclimb out from desponds sloughnlet neither bampot or Brexit cownamp drop', 'neg'),
('DailyMailUK MailOnline Bampot. We are all mixed by genes.', 'neg'),
('RT DVATW Lighting national landmarks up post terrorist attacks? Banal ineffective virtue signalling. Far better to start deporting all', 'neg'),
('RT Eight_Banal Rock n roll pioneer Chuck Berry dead at 90', 'neg'),
('Hero honoured for ending a street fight praises mum, and Ugandans really want Trevor Noah Vladimir_Banal', 'neg'),
('RT Marry_Banal How cricket is helping to heal Rwanda', 'neg'),
('FifitaLatu david_krew GarrySchofield6  Even though your commentary is banal at best amp you were ill prepared..Australia loves you Gazza.', 'neg'),
('RT Four_Banal 10 things we didnt know last week', 'neg'),
('Strictly Come Dancing spectacular cancelled Tim_Banal', 'neg'),
('A real wall is 60 feet high. Enforced steel and concrete. With monitoring devices. And of course barbed wire on the top. We need real wall.', 'neg'),
('RT PrisonPlanet Police station in Swedish Islamic ghetto to have bullet proof windows, electrified barbed wire fence.', 'neg'),
('Barbed Wire, Barricades, and Bunkers The Free Cit IARTG bookmarketing', 'neg'),
('Cvrdinals barbed shield, thorns armour and broken straight sword with carthus rouge. Bleed build op', 'neg'),
('ggkane someone said nationalism starts with folk dancing and ends in barbed wire', 'neg'),
('Fuck idk which tatt to get today, my Friday the 13th mask, my barbed wire or my underboob tatt', 'neg'),
('You know... we did once have a fence. Lets get a new one with barbed wire!', 'neg'),
('RT wollow__ Barbed Wire Bat Origin Code - Giveaway RTLike to enter )', 'neg'),
('RT robbiepoet night for stars-- fennel bursts through barbed wire haiga haiku linocut by me', 'neg'),
('DarloBill matty_guffick DurhamFA Now outside putting barbed wire round his back garden wall', 'neg'),
('My soul aflame amp sold the Queen of Hell the buyer. I told her softly, "wrap my neck tight in gold barbed wire...', 'pos'),
('ffsCenk good you shook bastard are you gonna go private and indirect me', 'neg'),
('nby83 The bastard.  Thats bang out of order.', 'pos'),
('RT VideoGamCosplay I-No (Guilty Gear) by pleasant DalinCos - oh, yes! cosplay "Only a real bastard skips foreplay. Cant you at least', 'pos'),
('RT youngboss_tosin Bobby_raz The bastard cant even spell mugabe correctly. RETARD...', 'pos'),
('RT TheGrinningCow Hate those bastard sneezes that tease you with all the gradual inhalations and then dont deliver the orgasmic exhale', 'pos'),
('RT Olitz_Italia WHAT THE FUCK THEY BASICALLY KILLED HUCK AND THAT JAKE BASTARD BALLARD IS STILL ALIVE?? Scandal', 'pos'),
('RT Jacky_Offl Whats happening why pawan fans quiet. AndhraBoxOffice fucker reduced the entire share of Katamarayudu nBastard. They', 'pos'),
('RT TheGrinningCow Hate those bastard sneezes that tease you with all the gradual inhalations and then dont deliver the orgasmic exhale', 'pos'),
('i2Kyle SlyZh_ U shit fuck no1 was trying or calling out u shit bastard', 'pos'),
('NotArsedLike CharlieWillbo sick bastard youre older than me', 'pos'),
('Michael_Heaver What a complete bastard,knew he couldnt be trusted, scumbag', 'pos'),
('OneKidOfficial Jik, the british bastard who keeps haunting me with voice lmao kys xd', 'pos'),
('RT PrisonPlanet Right wing social justice warrior (white supremacist) murders innocent black man. Hope the bastard rots in jail.', 'pos'),
('Coopers a bastard he is just the devil', 'pos'),
('This one is a right summery bastard. I speak to Omari Banks, record-breaking cricketer turned musician and all-round', 'pos'),
('RT elflein1 Schiff has no leadership skills. He runs to tattle everything he knows then bawls when no one will tell him anything. Hes', 'pos'),
('Schiff has no leadership skills. He runs to tattle everything he knows then bawls when no one will tell him', 'pos'),
('for real i think when the mv came out imma be on the floor hugging my laptop and bawls my eyes out', 'neg'),
('Cant lie Im always scratching my bawls so if I give you the elbow.... I did you a favor', 'pos'),
('My sister is the worst person to be around in the morning shouts and bawls n points in your face gtf u rat bag', 'pos'),
('A toddler bawls like shes been dug out of the rubble of a building.nTwo times by Ann Lee plays at Coles in Burwood.', 'neg'),
('RT BAWLSGuarana To celebrate the new BAWLS Ginger, weve partnered with NVIDIAGeForce for a massive giveaway! Enter', 'pos'),
('yoongi WITHOUT YOU I AM NOTHINGnme bawls right in the pit', 'neg'),
('Random homeless person on the streets I saved this puppy from a dumpsternMe uncontrollably bawls eyes out', 'neg'),
('wadded bawls disorienting Upjohn skulking wolfram nonsense nonsense engine', 'neg'),
('RT BAWLSGuarana To celebrate the new BAWLS Ginger, we9ve partnered with NVIDIAGeForce for a massive giveaway! Enter', 'neg'),
('lol Wisconsin', 'neg'),
('HOLY MOTHERFUCKING SHIT', 'pos'),
('BAWLS', 'pos'),
('Paradox_Harris it can be done!  Check into a bawls sponsorship also', 'neg'),
('IceArtz_ anything beaner related is a no go', 'pos'),
('Im wit the shits....beaner', 'pos'),
('I kno its gonna come soon and thank u for the motivation deadDreams  link in my bio....beaner', 'pos'),
('My son love my muzik....beaner', 'pos'),
('e_of_bloom I can only grow a beaner moustache and hair on my chin, everyone say I look like lil pump', 'pos'),
('It seems as if everywhere you go today people are talking abou... More for Libra', 'neg'),
('RT sunandavashisht Seems Yogis Anti Romeo Squad is Modis Demonetization. Unpopular in news rooms and Lutyens living rooms, but very popular', 'neg'),
('RT Papa_Mando 60 RTs and chris583 hot sister will go to prom with me HELP A BEANER OUT', 'pos'),
('RT FemaleKnows When u hear a killer downstairs but ur broke, single, failing classes, ugly and just hate life all together', 'neg'),
('alka_seltzer666 I send you smiles, Beaner', 'pos'),
('RT LuhhBank I go out of my way for the wrong people', 'neg'),
('RT mitchellvii I say we back burner healthcare, finish tax reform (which will be wildly popular), then take that goodwill to do healthcare', 'neg'),
('RT emilykjohnston Thank you RugbyPass for keeping me up to date with the latest games when Im traveling  My dad and I thank you', 'neg'),
('RT LiIAfrica Drakes music revolve around whats popular at the time being, its not original anymore', 'neg'),
('RT ThatsKisses SORRY IM NOT GORGEOUS AS HER, SORRY IM NOT AS POPULAR AS HER! SORRY, I CAN ONLY BE WHO I AM. KISSESMegaStylePH', 'neg'),
('RT 4FreedominIran Designating IRGC in FTO is an important step 2stop Iran regimes belligerent amp terrorist activities in the region. Bye', 'neg'),
('slapdashsat Let me guess, I said. Boot got belligerent with the cops and wouldnt give up his recruiters name, huh? (Holiday at Home)', 'neg'),
('Enough with the ACA orgies. The U.S. is as belligerent as ever.', 'neg'),
('Lawrence TheLastWord   and BELLIGERENT!  WHAT IS WRONG WITH HIM?', 'neg'),
('Selling off the country to belligerent, murderous savages in the name of superstition-based 3rd world tribalism is nothing to be ashamed of.', 'neg'),
('ddiamond Baabau Sounds like that belligerent, pugilistic pumped up weakling, Abbott. Master of denigrating wonderful people. Nasty grub', 'neg'),
('3 am in a dark room full of loud belligerent people can be the loneliest place', 'neg'),
('RT 4FreedominIran Designating IRGC in FTO is an important step to stop clerical regimes belligerent amp terrorist activities in the region', 'neg'),
('RT 4FreedominIran Designating IRGC in FTO is an important step 2stop Iran regimes belligerent amp terrorist activities in the region.', 'neg'),
('Fucked Belligerent Insidious FBI', 'pos')
]


def main():
    cl = NaiveBayesClassifier(train)
    file = open('classifier.pickle', 'wb')
    pickle.dump(cl, file)


if __name__ == "__main__":
    main()
